// SPDX-License-Identifier: AGPL-3.0-or-later
#include "CsoundExporter.h"

bool CsoundExporter::exportToFile(
    const std::vector<std::unique_ptr<Partial>>& partials,
    const Options&                               opts,
    const juce::File&                            outputFile)
{
    Mode mode = opts.mode;

    // Auto-select mode based on average breakpoints per partial
    if (partials.empty())
        return false;

    size_t totalBps = 0;
    for (const auto& p : partials)
        totalBps += p->breakpoints.size();
    const double avgBps = static_cast<double>(totalBps) / partials.size();

    if (mode == Mode::TableBased && avgBps <= opts.autoModeThreshold)
        mode = Mode::Inline;

    auto stream = outputFile.createOutputStream();
    if (stream == nullptr)
        return false;

    const bool ok = (mode == Mode::TableBased)
                        ? exportTableBased(partials, opts, *stream)
                        : exportInline(partials, opts, *stream);

    if (ok && opts.writeOrchestra) {
        juce::File orcFile = outputFile.withFileExtension("orc");
        if (auto orcStream = orcFile.createOutputStream())
            writeOrchestra(*orcStream);
    }

    return ok;
}

bool CsoundExporter::exportTableBased(
    const std::vector<std::unique_ptr<Partial>>& partials,
    const Options&                               opts,
    juce::OutputStream&                          out)
{
    out << "; Csound score — generated by PartialEditor (table mode)\n\n";

    int tableIdx = static_cast<int>(opts.startTableIdx);
    for (const auto& p : partials) {
        // f-statement for frequency table
        out << "f" << tableIdx << " 0 " << static_cast<int>(p->breakpoints.size() * 2) << " -2";
        for (const auto& bp : p->breakpoints)
            out << " " << juce::String(bp.time, 6) << " " << juce::String(bp.frequency, 4);
        out << "\n";

        // f-statement for amplitude table
        out << "f" << (tableIdx + 1) << " 0 " << static_cast<int>(p->breakpoints.size() * 2) << " -2";
        for (const auto& bp : p->breakpoints)
            out << " " << juce::String(bp.time, 6) << " " << juce::String(bp.amplitude, 6);
        out << "\n";

        // i-statement
        out << "i1 " << juce::String(p->startTime(), 6)
            << " "   << juce::String(p->duration(), 6)
            << " "   << tableIdx << " " << (tableIdx + 1) << "\n\n";

        tableIdx += 2;
    }
    return true;
}

bool CsoundExporter::exportInline(
    const std::vector<std::unique_ptr<Partial>>& partials,
    const Options&                               /*opts*/,
    juce::OutputStream&                          out)
{
    out << "; Csound score — generated by PartialEditor (inline linseg mode)\n\n";

    for (const auto& p : partials) {
        const auto& bps    = p->breakpoints;
        const int   numSeg = static_cast<int>(bps.size()) - 1;

        out << "i1 " << juce::String(p->startTime(), 6)
            << " "   << juce::String(p->duration(), 6)
            << " "   << numSeg;

        for (size_t i = 0; i < bps.size(); ++i) {
            out << " " << juce::String(bps[i].amplitude, 6)
                << " " << juce::String(bps[i].frequency, 4);
            if (i + 1 < bps.size())
                out << " " << juce::String(bps[i + 1].time - bps[i].time, 6);
        }
        out << "\n";
    }
    return true;
}

void CsoundExporter::writeOrchestra(juce::OutputStream& out)
{
    out <<
        "; PartialEditor template orchestra\n"
        "; Replace the oscili sine generator with your instrument of choice.\n\n"
        "sr = 48000\n"
        "ksmps = 64\n"
        "nchnls = 2\n"
        "0dbfs = 1\n\n"
        "instr 1\n"
        "  iFreqTable = p4\n"
        "  iAmpTable  = p5\n"
        "  kfreq  tablei timeinsts(), iFreqTable, 1\n"
        "  kamp   tablei timeinsts(), iAmpTable,  1\n"
        "  asig   oscili kamp, kfreq, 1\n"
        "  outs   asig, asig\n"
        "endin\n";
}