/* config.h — manually configured for macOS (arm64 / x86_64).
 * Generated by PartialEditor's CMake build in place of autoconf output.
 * Only the defines actually used by Loris source are set here.
 */

/* No FFTW — Loris will use its internal fftsg.c implementation. */
#define HAVE_FFTW3_H 0
#define HAVE_FFTW_H  0

/* Standard POSIX / C headers present on macOS 11+ */
#define HAVE_DLFCN_H    1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H   1
#define HAVE_STDINT_H   1
#define HAVE_STDLIB_H   1
#define HAVE_STRINGS_H  1
#define HAVE_STRING_H   1
#define HAVE_SYS_STAT_H  1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H   1
#define STDC_HEADERS    1

/* Math environment */
#define HAVE_M_PI    1
#define HAVE_ISFINITE 1

/* No Python bindings */
#define HAVE_PYTHON_H 0

/* Package info */
#define PACKAGE        "loris"
#define PACKAGE_NAME   "Loris"
#define PACKAGE_STRING "Loris 1.9"
#define PACKAGE_TARNAME "loris"
#define PACKAGE_VERSION "1.9"
#define VERSION        "1.9"
#define PACKAGE_BUGREPORT "loris@cerlsoundgroup.org"